version: "3.8"

services:
  proxy:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
      args:
        ENABLED_MODULES: brotli
    command: nginx
    volumes:
      - ./config/nginx/development/:/etc/nginx/:z
#    depends_on:
#      - gateway-service
    networks:
      - proxy-network

networks:
  proxy-network:
