eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://discovery-service:8761/eureka}

logging:
  level:
    com.netflix.eureka: OFF
    discovery: OFF